### ISSUE TITLE
tn generate doesn't work anymore

### ISSUE THREAD

**Issue by SquirrelMobile** [jasonkneen/tn#51]
Hello Fokke,

I use TN everyday, it seems that with the last version of XCODE, the generate function doesn't work anymore. I've try to reset my .tn.json and the new receipes are not added.

**Comment by FokkeZB** [comment]
What version of Xcode do you use and what error do you see, if any?

I've seen no issues with Xcode Version 8.2.1 (8C1002).

**Comment by SquirrelMobile** [comment]
Hi,

I'm using Xcode 8.1
Build version 8B62
There is no error, just it didn't save the new recipe when i install new simulators.

**Comment by FokkeZB** [comment]
Ah, I can see that indeed `ti info -o json` no longer returns the sims.

@hansemannn any idea if this was removed from the `ti` CLI?

**Comment by SquirrelMobile** [comment]
Ok so it's a regression ? I must downgrade my CLI version to make it works ?

**Comment by FokkeZB** [comment]
I dunno, it seems like a change in the OSS `ti` CLI. I haven't been using Ti much lately, so I have no idea when this changed. Could you try downgrading to previous minor/major versions (`npm info ti`) to see what the last version that worked is?

@hansemannn @jasonkneen do you have any clues?

**Comment by hansemannn** [comment]
It [does return the sims](https://gist.github.com/hansemannn/d011ea6d51f4a3cb8c3cc46cce053261) for me, but probably the access to them changed.

**Comment by FokkeZB** [comment]
Thanks @hansemannn. Then it looks like @SquirrelMobile (and me - but my env is probably outdated) has a bug which causes the CLI not to include that data anymore.

@SquirrelMobile, what SDK version do you have selected (`ti sdk select`) and what Java version installed?

**Comment by john-stephens** [comment]
@SquirrelMobile You may need to run `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` in order to get `ti generate` to find the XCode Simulators. I had to do this for a new install of XCode 10.
